apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: frontend
          image: {{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}
          ports:
            - containerPort: {{ .Values.image.frontend.port }}
          env:
            - name: BACKEND_URL
              value: "http://{{ .Release.Name }}-backend-service:{{ .Values.image.backend.port }}"
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
---


